### ISSUE TITLE
I can't find the data

### ISSUE THREAD

**Issue by ZealYa** [zcajiayin/Learning-D2D-task-off-loads#1]
Hello， could you give me the data？

g = subprocess.Popen(['grep','-E', 'bluetooth\|found|wifi\|connected|bluetooth\|found.*rssi|wifi\|connected.*rssi|battery\|level|timeinstates', '/usr/666Users/'+n], stdout = subprocess.PIPE)

**Comment by zcaicaros** [comment]
Hi,

This dataset is confidential and subjected to the project ["Device Analyzer for Android"](https://deviceanalyzer.cl.cam.ac.uk/). As the official [site](https://deviceanalyzer.cl.cam.ac.uk/) saying "Thank you to everyone who contributed to DeviceAnalyzer. We regretfully announce that the project is now closed, and we are no longer accepting new users or new requests for the dataset."

So I can not provide the dataset.
